"use client";
import { useState,useEffect,Suspense } from "react";
import { useRouter,useSearchParams } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { collection,query,where,onSnapshot } from "firebase/firestore";
import { LayoutDashboard,Layers3,ChartNoAxesCombined,CreditCard,Settings,ArrowUpRight,ArrowRight,Plus,Eye,MousePointer2,Percent,Wallet,Bell,ChevronRight,LogOut,Clock3,TrendingUp,ShieldCheck,Search,Sparkles,CircleHelp,Check } from "lucide-react";
import { db } from "@/lib/firebase";
import { clientPost } from "@/lib/client-api";
import { useAuth } from "@/contexts/AuthContext";
import { useLang } from "@/contexts/LangContext";
import type { Lang } from "@/lib/i18n";
import type { Ad,Transaction } from "@/types";
import { milliseconds,rankAds } from "@/lib/auction";
import { Brand,pick,money,categoryName,categoryNames,usePublicAds,LoadingState,type PublicAd } from "./shared";
import { DEMO_NOW,demoAds,demoTransactions,demoStats,demoPublic,type DailyStat } from "./dashboard-data";
import AdList,{adStatus,AdAction} from "./AdList";
import PerformanceChart from "./PerformanceChart";

type Screen="overview"|"ads"|"rankings"|"payments"|"settings"|"review";
const screens:Screen[]=["overview","ads","rankings","payments","settings","review"];
function useAccountData(uid?:string){
 const [ads,setAds]=useState<Ad[]>([]);const [txs,setTxs]=useState<Transaction[]>([]);const [stats,setStats]=useState<DailyStat[]>([]);
 const [loaded,setLoaded]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{
  if(!uid)return;
  const fail=()=>{setError("Account data could not be loaded.");setLoaded(true);};
  const unsubAds=onSnapshot(query(collection(db,"ads"),where("advertiserUID","==",uid)),snap=>{setAds(snap.docs.map(doc=>({id:doc.id,...doc.data()} as Ad)).sort((a,b)=>milliseconds(b.createdAt)-milliseconds(a.createdAt)));setLoaded(true);},fail);
  const unsubTxs=onSnapshot(query(collection(db,"transactions"),where("uid","==",uid)),snap=>setTxs(snap.docs.map(doc=>({id:doc.id,...doc.data()} as Transaction)).sort((a,b)=>milliseconds(b.createdAt)-milliseconds(a.createdAt))),fail);
  const unsubStats=onSnapshot(query(collection(db,"dailyStats"),where("uid","==",uid)),snap=>setStats(snap.docs.map(doc=>({id:doc.id,...doc.data()} as DailyStat))),fail);
  return()=>{unsubAds();unsubTxs();unsubStats();};
 },[uid]);
 return {ads,txs,stats,loaded,error};
}
function NoAds({lang,demo=false}:{lang:Lang;demo?:boolean}){
 return <div className="p-empty"><span className="p-brand-avatar violet"><Layers3 size={22}/></span><h2>{pick(lang,"Birinchi reklamangizdan boshlang","Start with your first ad","Начните с первого объявления")}</h2><p>{pick(lang,"Rasm, qisqa matn va taklifingizni kiriting. Natijalar shu yerda jamlanadi.","Add an image, a short description and your bid. Your results will come together here.","Добавьте изображение, описание и ставку. Все результаты будут собраны здесь.")}</p><Link className="p-btn p-btn-primary" href={demo?"/auth":"/create"}>{pick(lang,"Reklama yaratish","Create an ad","Создать объявление")}<Plus size={16}/></Link></div>;
}
function Rankings({ads,lang,myAds,demo,now}:{ads:PublicAd[];lang:Lang;myAds:Ad[];demo:boolean;now:number}){
 const [category,setCategory]=useState("all");
 const scoped=rankAds(ads.filter(ad=>category==="all"||ad.category===category),now);
 const position=(ad:PublicAd)=>rankAds(ads.filter(item=>item.category===ad.category),now).findIndex(item=>item.id===ad.id)+1;
 return <><p style={{fontSize:12,color:"#a08cb0",marginBottom:20}}>{pick(lang,"Kunlik taklif yuqori bo‘lsa — o‘rin yuqori. Teng stavkada avval faollashgan reklama oldinda.","Higher daily bids rank first. Equal bids favor the earlier activation.","Выше дневная ставка — выше позиция. При равных ставках приоритет у более ранней активации.")}</p><div className="p-filters"><button aria-pressed={category==="all"} onClick={()=>setCategory("all")}>{pick(lang,"Barchasi","All categories","Все")}</button>{Object.keys(categoryNames).map(key=><button key={key} aria-pressed={category===key} onClick={()=>setCategory(key)}>{categoryName(key,lang)}</button>)}</div><div className="p-panel"><div className="p-table-scroll"><table className="p-table"><thead><tr><th>#</th><th>{pick(lang,"Reklama","Advertisement","Объявление")}</th><th>{pick(lang,"Kunlik taklif","Daily bid","Дневная ставка")}</th><th>{pick(lang,"Amal","Action","Действие")}</th></tr></thead><tbody>{scoped.map((ad)=>{const mine=myAds.find(item=>item.id===ad.id);return <tr key={ad.id}><td><span className="p-position">#{position(ad)}</span></td><td><div className="p-ad-name"><span className="p-ad-thumbnail">{ad.title[0]}</span><div><strong>{ad.title}{mine?" · "+pick(lang,"Siz","You","Вы"):""}</strong><small>{categoryName(ad.category,lang)}</small></div></div></td><td>{money(ad.dailyBidCents)}</td><td>{mine?<AdAction ad={mine} now={now} lang={lang} demo={demo}/>:<Link className="p-table-action" href={demo?"/auth":`/create?category=${ad.category}&minBid=${ad.dailyBidCents+1}`}>{pick(lang,"Taklif berish","Place a bid","Сделать ставку")}<ArrowUpRight size={12}/></Link>}</td></tr>;})}</tbody></table></div>{!scoped.length&&<div className="p-empty"><Layers3 size={24}/><p>{pick(lang,"Bu toifada hali faol reklama yo‘q.","No active ads in this category yet.","В этой категории пока нет активных объявлений.")}</p><Link className="p-btn p-btn-secondary" href={demo?"/auth":"/create"}>{pick(lang,"Birinchi bo‘ling","Be the first","Будьте первым")}</Link></div>}</div></>;
}
function Profile({lang,name,email,demo}:{lang:Lang;name:string;email:string;demo:boolean}){
 const [value,setValue]=useState(name);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage("");try{if(!demo)await clientPost("/api/profile",{displayName:value});setMessage(pick(lang,demo?"Demo ma’lumoti yangilandi.":"Saqlandi.",demo?"Demo updated.":"Saved.",demo?"Демо обновлено.":"Сохранено."));}catch{setMessage(pick(lang,"Saqlanmadi. Qayta urinib ko‘ring.","Could not save. Please retry.","Не удалось сохранить."));}finally{setBusy(false);}}
 return <div className="p-profile-grid"><form className="p-panel" onSubmit={save}><h2>{pick(lang,"Brend profili","Brand profile","Профиль бренда")}</h2><label className="p-field">{pick(lang,"Brend nomi","Brand name","Название бренда")}<input required maxLength={80} value={value} onChange={event=>setValue(event.target.value)}/></label><label className="p-field">Email<input disabled value={email}/><small>{pick(lang,"Google hisobingiz bilan bog‘langan.","Linked to your Google account.","Связан с аккаунтом Google.")}</small></label><button className="p-btn p-btn-primary" disabled={busy}>{pick(lang,busy?"Saqlanmoqda…":"O‘zgarishlarni saqlash",busy?"Saving…":"Save changes",busy?"Сохранение…":"Сохранить")}</button>{message&&<p role="status" style={{fontSize:12,marginTop:15,color:"#cdb0e4"}}>{message}</p>}</form><section className="p-panel"><ShieldCheck size={25} color="#bc9ddd"/><h2 style={{marginTop:20}}>{pick(lang,"Hisobingiz nazoratingizda","Your account, in your control","Ваш аккаунт под контролем")}</h2><p style={{fontSize:12,color:"#a48ab4"}}>{pick(lang,"Reklama va to‘lov ma’lumotlaringiz faqat sizga hamda vakolatli administratorga ochiq. Pul yechish faqat alohida to‘lov oynasida amalga oshiriladi.","Your ad and payment records are private to you and authorized administrators. Payments are made through a separate checkout.","Данные рекламы и платежей доступны только вам и уполномоченным администраторам. Оплата производится в отдельном окне.")}</p><Link className="p-text-link" style={{marginTop:20}} href="/terms">{pick(lang,"Xizmat shartlari","Service terms","Условия сервиса")}<ArrowUpRight size={15}/></Link></section></div>;
}
function Review({lang}:{lang:Lang}){
 const {firebaseUser}=useAuth();const [ads,setAds]=useState<Ad[]>([]);const [paymentIssues,setPaymentIssues]=useState<Array<{id:string;title:string;externalTxId:string;status:string;totalPaidCents:number}>>([]);const [message,setMessage]=useState("");const [revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;firebaseUser?.getIdToken().then(token=>fetch("/api/admin/review",{headers:{Authorization:`Bearer ${token}`}})).then(async res=>{if(!res?.ok)throw new Error();const data=await res.json();if(active){setAds(data.ads);setPaymentIssues(data.paymentIssues||[]);}}).catch(()=>{if(active)setMessage(pick(lang,"Tekshiruv navbati yuklanmadi.","Review queue unavailable.","Очередь проверки недоступна."));});return()=>{active=false;};},[firebaseUser,revision,lang]);
 async function decide(adId:string,decision:"approve"|"reject",reason=""){try{await clientPost("/api/admin/review",{adId,decision,reason});setRevision(value=>value+1);setMessage("");}catch(error){setMessage(error instanceof Error?error.message:"Failed");}}
 return <div className="p-panel">{message&&<div className="p-error" role="alert">{message}</div>}{paymentIssues.length>0&&<section style={{padding:24,borderBottom:"1px solid var(--p-line)"}}><h2>{pick(lang,"To‘lov tekshiruvi talab etiladi","Payments needing review","Платежи требуют проверки")}</h2><p className="p-flow-note">{pick(lang,"Provayderdagi to‘lov va qaytarish holatini qo‘lda solishtiring. Bu navbatdan avtomatik ravishda reklama faollashtirilmaydi.","Reconcile each provider payment and refund manually. This queue never activates an ad automatically.","Сверьте платежи и возвраты вручную. Очередь не активирует объявления автоматически.")}</p>{paymentIssues.map(issue=><div key={issue.id} className="p-attention-item"><b>{issue.title}</b><span>{issue.status} · {money(issue.totalPaidCents||0)}</span><small>{issue.id} · {issue.externalTxId}</small></div>)}</section>}{ads.map(ad=><ReviewItem key={ad.id} ad={ad} lang={lang} onDecide={decide}/>)}{!ads.length&&<div className="p-empty"><Check size={26}/>{pick(lang,"Tekshirish uchun reklama yo‘q.","No ads awaiting review.","Нет объявлений на проверке.")}</div>}</div>;
}
function ReviewItem({ad,lang,onDecide}:{ad:Ad;lang:Lang;onDecide:(id:string,decision:"approve"|"reject",reason?:string)=>Promise<void>}){
 const [reason,setReason]=useState("");const [busy,setBusy]=useState(false);
 async function run(decision:"approve"|"reject"){setBusy(true);await onDecide(ad.id,decision,reason);setBusy(false);}
 return <article style={{padding:24,borderBottom:"1px solid var(--p-line)"}}><h3>{ad.title}</h3><p style={{fontSize:12,margin:"10px 0"}}>{ad.description}</p>{ad.imageURL&&<Image src={ad.imageURL} alt={ad.title} width={180} height={130} unoptimized style={{borderRadius:8,maxHeight:130,objectFit:"cover"}}/>}<a href={ad.destinationURL} target="_blank" rel="noopener noreferrer" className="p-text-link">{ad.destinationURL}<ArrowUpRight size={14}/></a><label className="p-field">{pick(lang,"Rad etish sababi","Rejection reason","Причина отклонения")}<input value={reason} maxLength={500} onChange={event=>setReason(event.target.value)}/></label><div style={{display:"flex",gap:12}}><button className="p-btn p-btn-primary" disabled={busy} onClick={()=>run("approve")}>{pick(lang,"Tasdiqlash","Approve","Одобрить")}</button><button className="p-btn p-btn-secondary" disabled={busy||reason.trim().length<5} onClick={()=>run("reject")}>{pick(lang,"Rad etish","Reject","Отклонить")}</button></div></article>;
}
function DashboardContent({demo=false}:{demo?:boolean}){
 const {lang,setLang}=useLang();const router=useRouter();const params=useSearchParams();
 const {firebaseUser,userProfile,loading,profileError,isAdmin,signOut,refreshProfile}=useAuth();
 const account=useAccountData(demo?undefined:firebaseUser?.uid);const publicData=usePublicAds(!demo);
 const [clock,setClock]=useState(()=>Date.now());const [filter,setFilter]=useState("all");const [search,setSearch]=useState("");
 useEffect(()=>{if(demo)return;const timer=setInterval(()=>setClock(Date.now()),30000);return()=>clearInterval(timer);},[demo]);
 useEffect(()=>{if(!demo&&!loading&&!firebaseUser)router.replace("/auth");},[demo,loading,firebaseUser,router]);
 const requested=params.get("view") as Screen;const screen=screens.includes(requested)&&(requested!=="review"||isAdmin)?requested:"overview";
 const setScreen=(view:Screen)=>router.replace(`/dashboard${demo?"/demo":""}?view=${view}`,{scroll:false});
 const now=demo?DEMO_NOW:clock;const ads=demo?demoAds:account.ads;const txs=demo?demoTransactions:account.txs;const stats=demo?demoStats:account.stats;
 const publicAds=demo?demoPublic:publicData.ads;
 const name=demo?"Nova Studio":userProfile?.displayName||firebaseUser?.displayName||"";
 const nav=[{id:"overview" as Screen,icon:LayoutDashboard,label:pick(lang,"Umumiy holat","Overview","Обзор")},{id:"ads" as Screen,icon:Layers3,label:pick(lang,"Reklamalarim","My campaigns","Мои объявления")},{id:"rankings" as Screen,icon:ChartNoAxesCombined,label:pick(lang,"Reyting","Rankings","Рейтинг")},{id:"payments" as Screen,icon:CreditCard,label:pick(lang,"To‘lovlar","Payments","Платежи")},{id:"settings" as Screen,icon:Settings,label:pick(lang,"Sozlamalar","Settings","Настройки")}];
 if(isAdmin&&!demo)nav.push({id:"review",icon:ShieldCheck,label:pick(lang,"Moderatsiya","Moderation","Модерация")});
 const current=nav.find(item=>item.id===screen)!;
 const title=screen==="overview"?pick(lang,"Salom, "+name+" 👋","Hello, "+name+" 👋","Здравствуйте, "+name+" 👋"):current.label;
 const impressions=ads.reduce((sum,ad)=>sum+(ad.impressions||0),0);const clicks=ads.reduce((sum,ad)=>sum+(ad.clicks||0),0);
 const spent=txs.reduce((sum,tx)=>sum+(tx.type==="refund"?-tx.amountCents:tx.amountCents),0);
 const attention=ads.filter(ad=>adStatus(ad,now)==="pending"||ad.status==="pending_verification"||ad.paymentReviewRequired||
  (adStatus(ad,now)==="active"&&(milliseconds(ad.expiresAt)-now<3*86400000||rankAds(publicAds.filter(item=>item.category===ad.category),now).findIndex(item=>item.id===ad.id)>0)));
 const filteredAds=ads.filter(ad=>(filter==="all"||adStatus(ad,now)===filter)&&ad.title.toLowerCase().includes(search.toLowerCase()));
 if(!demo&&(loading||!firebaseUser))return <div className="p-workspace"><LoadingState label={pick(lang,"Kabinet yuklanmoqda…","Loading your workspace…","Загрузка кабинета…")}/></div>;
 return <div className="p-workspace"><aside className="p-sidebar"><Brand/><span className="p-sidebar-label">{pick(lang,"ISH MAYDONI","WORKSPACE","РАБОЧЕЕ ПРОСТРАНСТВО")}</span><nav aria-label={pick(lang,"Kabinet menyusi","Workspace navigation","Навигация кабинета")}>{nav.map(({id,icon:Icon,label})=><button key={id} className={screen===id?"is-active":""} aria-current={screen===id?"page":undefined} onClick={()=>setScreen(id)}><Icon/>{label}{id==="ads"&&<span className="p-nav-count">{ads.length}</span>}</button>)}</nav><div className="p-sidebar-bottom"><div className="p-sidebar-tip"><Sparkles size={21}/><b>{pick(lang,"Keyingi qadam sizniki","Make your next move","Ваш следующий шаг")}</b><p>{pick(lang,"Taklifingizni yangilang. Brendingizga ko‘proq ko‘rinish bering.","Update your bid. Give your brand a more prominent position.","Обновите ставку. Сделайте бренд заметнее.")}</p><Link href={demo?"/auth":"/create"}>{pick(lang,"Reklama joylashtirish","Launch an ad","Разместить рекламу")}<ArrowUpRight size={14}/></Link></div><Link className="p-text-link" style={{padding:12,fontSize:11}} href="/how-it-works"><CircleHelp size={15}/>{pick(lang,"Yordam markazi","How it works","Как это работает")}</Link><button onClick={async()=>{if(!demo)await signOut();router.push("/");}}><LogOut size={15}/>{pick(lang,demo?"Bosh sahifa":"Chiqish",demo?"Back home":"Sign out",demo?"На главную":"Выйти")}</button></div></aside>
 <div className="p-work-area"><header className="p-work-header"><div className="p-breadcrumb"><span>Primio</span><ChevronRight size={12}/><b>{current.label}</b></div><div className="p-work-tools"><select className="p-lang" aria-label={pick(lang,"Til","Language","Язык")} value={lang} onChange={event=>setLang(event.target.value as Lang)}><option value="uz">UZ</option><option value="en">EN</option><option value="ru">RU</option></select><button className="p-icon-btn" aria-label={pick(lang,"Bildirishnomalar","Notifications","Уведомления")} onClick={()=>setScreen("overview")}><Bell size={17}/></button><button className="p-work-avatar" aria-label={pick(lang,"Profil","Profile","Профиль")} onClick={()=>setScreen("settings")}>{name.charAt(0)||"P"}</button></div></header>
 <div className="p-work-content">{demo&&<div className="p-demo-banner"><Sparkles size={15}/><span>{pick(lang,"Demo kabinet · Barcha ko‘rsatkichlar namuna.","Demo workspace · All figures are sample data.","Демо-кабинет · Все показатели — пример.")}</span><Link href="/auth">{pick(lang,"O‘z hisobimni yaratish","Create my account","Создать аккаунт")}<ArrowUpRight size={13}/></Link></div>}
 <div className="p-page-heading"><div><h1>{title}</h1><p>{screen==="overview"?pick(lang,"Reklamalaringiz qanday ishlayotganini bir qarashda ko‘ring.","Here’s how your campaigns are doing.","Все результаты ваших объявлений — с первого взгляда."):pick(lang,"Brendingiz uchun muhim ma’lumotlar bir joyda.","Everything that matters to your brand, in one place.","Всё важное для вашего бренда — в одном месте.")}</p></div><Link className="p-btn p-btn-primary" href={demo?"/auth":"/create"}><Plus size={16}/>{pick(lang,"Yangi reklama","New campaign","Создать")}</Link></div>
 {!demo&&(profileError||account.error)&&<div className="p-error" role="alert">{pick(lang,"Ma’lumotlarni yuklab bo‘lmadi. Ulanishni tekshirib, qayta urinib ko‘ring.","Could not load your data. Check your connection and retry.","Не удалось загрузить данные. Проверьте соединение.")}<button onClick={refreshProfile}>{pick(lang,"Qayta urinish","Retry","Повторить")}</button></div>}
 {!demo&&publicData.error&&screen==="rankings"&&<div className="p-error" role="alert">{pick(lang,"Reyting vaqtincha mavjud emas.","Rankings are temporarily unavailable.","Рейтинг временно недоступен.")}<button onClick={publicData.retry}>{pick(lang,"Qayta urinish","Retry","Повторить")}</button></div>}
 {screen==="overview"&&<><div className="p-metric-grid">{[
  {label:pick(lang,"Jami ko‘rilish","Total impressions","Всего показов"),value:impressions.toLocaleString(),icon:Eye,hint:pick(lang,"Barcha reklamalar bo‘yicha","Across all campaigns","По всем объявлениям")},
  {label:pick(lang,"Jami bosish","Total clicks","Всего кликов"),value:clicks.toLocaleString(),icon:MousePointer2,hint:pick(lang,"Saytingizga o‘tishlar","Visits to your website","Переходы на ваш сайт")},
  {label:pick(lang,"Bosish ulushi · CTR","Click-through rate","Кликабельность · CTR"),value:(impressions?clicks/impressions*100:0).toFixed(2)+"%",icon:Percent,hint:pick(lang,"Bosishlar / ko‘rilishlar","Clicks / impressions","Клики / показы")},
  {label:pick(lang,"Jami to‘langan","Total paid","Всего оплачено"),value:money(spent),icon:Wallet,hint:pick(lang,"Qaytarishlar ayrilgan · USD","Refunds deducted · USD","За вычетом возвратов · USD")}
 ].map(({label,value,icon:Icon,hint})=><section className="p-metric-card" key={label}><div className="p-metric-top"><span>{label}</span><Icon/></div><strong className="p-metric-value">{value}</strong><small>{hint}</small></section>)}</div>
 <div className="p-overview-grid"><PerformanceChart stats={stats} lang={lang} now={now}/><section className="p-panel" id="attention"><div className="p-panel-heading"><div><h2>{pick(lang,"E’tiboringizga","Needs your attention","Обратите внимание")}</h2><p>{pick(lang,"Keyingi muhim qadamlar","Your next important steps","Следующие важные шаги")}</p></div><span className="p-nav-count">{attention.length}</span></div><div className="p-attention-list">{attention.slice(0,3).map(ad=>{const state=adStatus(ad,now);const expiry=state==="active"&&milliseconds(ad.expiresAt)-now<3*86400000;const Icon=expiry?Clock3:state==="active"?TrendingUp:ShieldCheck;const message=ad.paymentReviewRequired?pick(lang,"To‘lovni tekshirish kerak","Payment needs review","Платёж требует проверки"):state==="pending"?pick(lang,"Reklamangiz to‘lovni kutmoqda","Your ad is ready for payment","Объявление ожидает оплаты"):state==="pending_verification"?pick(lang,"Hisobingiz tekshirilmoqda","Your account is being reviewed","Аккаунт проверяется"):expiry?pick(lang,"Reklama muddati tugayapti","Your ad is ending soon","Срок скоро истекает"):pick(lang,"Yuqoriroq o‘ringa chiqing","Move up in your category","Поднимитесь в категории");return <div className="p-attention-item" key={ad.id}><span className="p-attention-icon"><Icon size={14}/></span><div><b>{message}</b><p>{ad.title}</p><AdAction ad={ad} now={now} lang={lang} demo={demo}/></div></div>;})}{!attention.length&&<div className="p-chart-empty" style={{minHeight:220}}><ShieldCheck size={27}/>{pick(lang,"Hammasi joyida","You’re all caught up","Всё в порядке")}<small>{pick(lang,"Muhim yangiliklar shu yerda paydo bo‘ladi.","Important updates will appear here.","Важные обновления появятся здесь.")}</small></div>}</div></section></div>
 <section className="p-panel"><div className="p-panel-heading"><div><h2>{pick(lang,"Reklamalaringiz","Your campaigns","Ваши объявления")}</h2><p>{ads.filter(ad=>adStatus(ad,now)==="active").length} {pick(lang,"ta faol reklama","active campaigns","активных объявлений")}</p></div><button onClick={()=>setScreen("ads")}>{pick(lang,"Barchasini ko‘rish","View all","Посмотреть все")}<ArrowRight size={13}/></button></div>{!demo&&!account.loaded?<LoadingState label={pick(lang,"Yuklanmoqda…","Loading…","Загрузка…")}/>:ads.length?<AdList ads={ads.slice(0,4)} publicAds={publicAds} lang={lang} now={now} demo={demo}/>:<NoAds lang={lang} demo={demo}/>}</section></>}
 {screen==="ads"&&<><label className="p-search"><Search size={16}/><input aria-label={pick(lang,"Reklama qidirish","Search campaigns","Поиск объявлений")} placeholder={pick(lang,"Reklama qidirish…","Search campaigns…","Поиск объявлений…")} value={search} onChange={event=>setSearch(event.target.value)}/></label><div className="p-filters">{[["all",pick(lang,"Barchasi","All","Все")],["active",pick(lang,"Faol","Active","Активные")],["pending",pick(lang,"To‘lov kutilmoqda","Awaiting payment","Ожидают оплаты")],["pending_verification",pick(lang,"Tekshiruvda","In review","На проверке")],["expired",pick(lang,"Tugagan","Expired","Завершены")],["rejected",pick(lang,"Rad etilgan","Rejected","Отклонены")]].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className="p-panel">{filteredAds.length?<AdList ads={filteredAds} publicAds={publicAds} lang={lang} now={now} demo={demo}/>:ads.length?<div className="p-empty">{pick(lang,"Mos reklama topilmadi.","No matching campaigns.","Подходящие объявления не найдены.")}</div>:<NoAds lang={lang} demo={demo}/>}</div></>}
 {screen==="rankings"&&<Rankings ads={publicAds} myAds={ads} lang={lang} demo={demo} now={now}/>}
 {screen==="payments"&&<><div className="p-metric-card" style={{maxWidth:340,marginBottom:25}}><div className="p-metric-top">{pick(lang,"Jami to‘langan","Total paid","Всего оплачено")}<Wallet/></div><strong className="p-metric-value">{money(spent)}</strong><small>{pick(lang,"To‘lovlar minus qaytarishlar · USD","Payments minus refunds · USD","Платежи за вычетом возвратов · USD")}</small></div><div className="p-panel"><div className="p-panel-heading"><h2>{pick(lang,"To‘lov tarixi","Payment history","История платежей")}</h2><CreditCard size={17} color="#9873b0"/></div>{txs.length?<div className="p-table-scroll"><table className="p-table"><thead><tr><th>{pick(lang,"Sana","Date","Дата")}</th><th>{pick(lang,"Reklama","Campaign","Объявление")}</th><th>{pick(lang,"Amal","Type","Операция")}</th><th>{pick(lang,"Summa","Amount","Сумма")}</th></tr></thead><tbody>{txs.map(tx=><tr key={tx.id}><td>{new Date(milliseconds(tx.createdAt)).toLocaleDateString(lang==="uz"?"uz-UZ":lang==="ru"?"ru-RU":"en-US")}</td><td>{ads.find(ad=>ad.id===tx.adId)?.title||tx.adId}</td><td>{tx.type==="refund"?pick(lang,"Qaytarish","Refund","Возврат"):tx.type==="bid_upgrade"?pick(lang,"Stavka oshirish","Bid increase","Повышение ставки"):tx.type==="renewal"?pick(lang,"Uzaytirish","Renewal","Продление"):pick(lang,"Joylashtirish","Placement","Размещение")}</td><td>{tx.type==="refund"?"−":""}{money(tx.amountCents)}</td></tr>)}</tbody></table></div>:<div className="p-empty"><CreditCard size={25}/>{pick(lang,"Hali to‘lovlar yo‘q.","No payments yet.","Платежей пока нет.")}</div>}</div><p style={{fontSize:11,color:"#8f769f",marginTop:20}}>{pick(lang,"To‘lov usullari va yakuniy summa to‘lov oynasida ko‘rsatiladi.","Available payment methods and the final charge are shown at checkout.","Доступные способы оплаты и итоговая сумма отображаются при оформлении платежа.")}</p></>}
 {screen==="settings"&&<><Profile key={name} lang={lang} name={name} email={demo?"hello@example.com":firebaseUser?.email||""} demo={demo}/><button className="p-btn p-btn-secondary" style={{marginTop:22}} onClick={async()=>{if(!demo)await signOut();router.push("/");}}><LogOut size={15}/>{pick(lang,demo?"Bosh sahifaga":"Hisobdan chiqish",demo?"Back home":"Sign out",demo?"На главную":"Выйти")}</button></>}
 {screen==="settings"&&isAdmin&&!demo&&<Link className="p-btn p-btn-secondary" style={{marginTop:18}} href="/dashboard?view=review"><ShieldCheck size={16}/>{pick(lang,"Moderatsiya navbati","Review queue","Очередь модерации")}</Link>}
 {screen==="review"&&isAdmin&&!demo&&<Review lang={lang}/>}
 </div></div><nav className="p-mobile-work-nav" aria-label={pick(lang,"Kabinet menyusi","Workspace navigation","Навигация кабинета")}>{nav.slice(0,5).map(({id,icon:Icon,label})=><button key={id} className={screen===id?"is-active":""} aria-current={screen===id?"page":undefined} onClick={()=>setScreen(id)}><Icon/><span>{label}</span></button>)}</nav></div>;
}
export default function Dashboard({demo=false}:{demo?:boolean}){return <Suspense fallback={<LoadingState label="Primio…"/>}><DashboardContent demo={demo}/></Suspense>;}
