"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, MoveUpRight, Check, ShieldCheck, ChartNoAxesCombined, SlidersHorizontal, Zap, Globe2, MousePointer2, Pause, Play, Plus, Layers3, Monitor, Utensils, Shirt, GraduationCap, HeartPulse, Building2, PartyPopper, Sparkles } from "lucide-react";
import { useLang } from "@/contexts/LangContext";
import { pick, money, Footer, categoryName } from "./shared";
import { CATEGORY_IDS } from "@/lib/auction";

const icons = [Monitor, Utensils, Shirt, GraduationCap, HeartPulse, Building2, PartyPopper, Sparkles];

export default function Landing() {
  const { lang } = useLang();
  const [bid, setBid] = useState(650);
  const [days, setDays] = useState(7);
  const [paused, setPaused] = useState(false);
  const [faq, setFaq] = useState<number | null>(0);
  const cards = [
    { id: "nova", name: "Nova Studio", bid: 900, letter: "N", tone: "lime" },
    { id: "you", name: pick(lang,"Sizning brendingiz","Your brand","Ваш бренд"), bid, letter: "P", tone: "violet" },
    { id: "orbit", name: "Orbit Academy", bid: 400, letter: "O", tone: "coral" }
  ].sort((a,b) => b.bid - a.bid || (a.id === "you" ? 1 : -1));
  const position = cards.findIndex(card => card.id === "you") + 1;
  const faqs = [
    [pick(lang,"Reklamam qayerda ko‘rinadi?","Where will my ad appear?","Где появится моя реклама?"),pick(lang,"Reklamangiz Primio’ning ochiq reklama katalogida va tanlangan toifa reytingida ko‘rinadi. Bu boshqa saytlar yoki ijtimoiy tarmoqlarga reklama tarqatish xizmati emas.","Your ad appears in Primio’s public directory and its category ranking. Placement does not include distribution to external sites or social networks.","В открытом каталоге Primio и рейтинге выбранной категории. Размещение не включает показ на сторонних сайтах и в социальных сетях.")],
    [pick(lang,"Reytingdagi o‘rin qanday belgilanadi?","How is my position determined?","Как определяется позиция?"),pick(lang,"Yuqoriroq kunlik taklif yuqoriroq o‘rin beradi. Teng takliflarda avvalroq faollashgan reklama oldinda turadi. Raqobatchilar stavkasini o‘zgartirsa, o‘rningiz ham o‘zgarishi mumkin.","Higher daily bids rank first. Equal bids are ordered by activation time, earlier first. Your position can change when competitors change their bids.","Выше дневная ставка — выше позиция. При равных ставках раньше активированное объявление выше. Позиция может измениться при новых ставках конкурентов.")],
    [pick(lang,"To‘lov va reklama muddati qachon boshlanadi?","When do I pay and when does my ad start?","Когда платить и когда начинается показ?"),pick(lang,"Avval reklama moderatsiyadan o‘tadi. Keyin tanlangan muddat uchun oldindan to‘laysiz. Yangi hisob qo‘shimcha tekshirilishi mumkin; reklama muddati faollashgan vaqtdan boshlanadi.","Moderation comes first, then prepayment for your selected period. New accounts may need an additional review; the paid period starts only when the ad is activated.","Сначала модерация, затем предоплата за выбранный период. Новые аккаунты могут пройти дополнительную проверку. Оплаченный срок начинается с активации.")],
    [pick(lang,"Birinchi o‘rin savdoni kafolatlaydimi?","Does first place guarantee sales?","Гарантирует ли первое место продажи?"),pick(lang,"Yo‘q. Siz katalogdagi joylashuvni sotib olasiz. Ko‘rilish, bosish va savdo natijalari auditoriya hamda reklamangizga bog‘liq. Haqiqiy ko‘rsatkichlarni kabinetda kuzatasiz.","No. You purchase placement in the directory. Views, clicks and sales depend on the audience and your ad. Track actual views and clicks in your dashboard.","Нет. Вы оплачиваете позицию в каталоге. Просмотры, клики и продажи зависят от аудитории и объявления. Реальные показатели доступны в кабинете.")],
    [pick(lang,"Taklifni keyin oshirish mumkinmi?","Can I raise my bid later?","Можно ли повысить ставку позже?"),pick(lang,"Ha. Faol reklamada stavkani oshirish mumkin. Yangi va eski stavka farqi qolgan kunlarga ko‘paytiriladi; to‘lovdan oldin aniq summa ko‘rsatiladi. Tugallanmagan kun to‘liq kun hisoblanadi.","Yes. Pay the difference between the new and old bid for the remaining days. Partial days count as a full day; the exact price is shown before checkout.","Да. Оплачивается разница между новой и старой ставкой за оставшиеся дни. Неполный день считается полным; сумма показана до оплаты.")]
  ];
  return <div className="p-site">
    <section className="p-hero p-container">
      <div className="p-hero-copy">
        <div className="p-eyebrow"><span className="p-status-dot"/>{pick(lang,"REKLAMANGIZ UCHUN YANGI O‘RIN","A NEW PLACE FOR YOUR BRAND","НОВОЕ МЕСТО ДЛЯ ВАШЕГО БРЕНДА")}</div>
        <h1>{pick(lang,"Ko‘rinish vaqti.","Time to be seen.","Время быть заметным.")}<br/><span className="p-gradient-text">{pick(lang,"Yuqoriga chiqing.","Rise to the top.","Поднимайтесь выше.")}<span className="p-title-star">✳</span></span></h1>
        <p className="p-hero-sub">{pick(lang,"Brendingizni kerakli toifada oldinga olib chiqing. Taklifingizni belgilang, o‘rningizni boshqaring va natijani kuzating.","Put your brand in front of the right category. Set your bid, own your position, and follow the results.","Выведите бренд вперёд в нужной категории. Задавайте ставку, управляйте позицией и следите за результатами.")}</p>
        <div className="p-hero-buttons"><Link className="p-btn p-btn-primary" href="/create">{pick(lang,"Reklama joylashtirish","Launch your ad","Разместить рекламу")}<ArrowUpRight size={19}/></Link>
          <Link className="p-text-link" href="/dashboard/demo"><span className="p-play"><Play size={13} fill="currentColor"/></span>{pick(lang,"Kabinetni ko‘rish","Explore the dashboard","Посмотреть кабинет")}</Link></div>
        <div className="p-hero-trust"><span><Check size={14}/>{pick(lang,"Kuniga $1 dan","From $1 / day","От $1 в день")}</span><span><Check size={14}/>{pick(lang,"Aniq reyting qoidalari","Transparent ranking","Прозрачный рейтинг")}</span><span><Check size={14}/>{pick(lang,"8 ta toifa","8 categories","8 категорий")}</span></div>
      </div>
      <div className={`p-scene ${paused ? "is-paused" : ""}`}>
        <div className="p-scene-orbit p-orbit-one"/><div className="p-scene-orbit p-orbit-two"/>
        <div className="p-scene-caption"><span className="p-mini-dot"/>{pick(lang,"INTERAKTIV NAMUNA","INTERACTIVE DEMO","ИНТЕРАКТИВНЫЙ ПРИМЕР")}</div>
        <div className="p-scene-floating">
          <div className="p-scene-world">
            <div className="p-scene-heading"><Layers3 size={18}/><span>{pick(lang,"Sizning keyingi o‘rningiz","Your next position","Ваша следующая позиция")}</span><span className="p-scene-heading-dots">•••</span></div>
            <div className="p-rank-stack">
              {cards.map((card,index) => <div key={card.id} className={`p-scene-card ${card.id === "you" ? "p-scene-yours" : ""}`} style={{ transform: `translate3d(0,${index * 91}px,${(3-index)*12}px)` }}>
                <span className="p-scene-rank">0{index+1}</span><div className={`p-brand-avatar ${card.tone}`}>{card.letter}</div>
                <div className="p-scene-card-name"><strong>{card.name}</strong><span>{card.id === "you" ? pick(lang,"Sizning reklamangiz","Your advertisement","Ваше объявление") : pick(lang,"Texnologiya","Technology","Технологии")}</span></div>
                <div className="p-scene-bid"><b>{money(card.bid)}</b><span>/{pick(lang,"kun","day","день")}</span></div>
                {card.id === "you" && <span className="p-your-card-arrow"><MoveUpRight size={13}/></span>}
              </div>)}
            </div>
            <div className="p-scene-floor"><span>PRIMIO</span><span>↑</span></div>
          </div>
          <div className="p-floating-win"><span className="p-win-icon"><ChartNoAxesCombined size={18}/></span><div><small>{pick(lang,"Sizning o‘rningiz","Your position","Ваша позиция")}</small><strong>#{position} <span>{pick(lang,"yuqoriga yo‘l ochiq","room to rise","путь наверх открыт")}</span></strong></div></div>
        </div>
        <div className="p-scene-controller">
          <div><span><SlidersHorizontal size={14}/>{pick(lang,"Taklifni o‘zgartirib ko‘ring","Try changing your bid","Попробуйте изменить ставку")}</span><button className="p-icon-btn" onClick={() => setPaused(!paused)} aria-label={paused ? pick(lang,"Animatsiyani boshlash","Play animation","Включить анимацию") : pick(lang,"Animatsiyani to‘xtatish","Pause animation","Остановить анимацию")}>{paused ? <Play size={14}/> : <Pause size={14}/>}</button></div>
          <label className="p-slider-label" htmlFor="hero-bid"><span>{pick(lang,"Kunlik taklif","Daily bid","Дневная ставка")}</span><b>{money(bid)}</b></label>
          <input id="hero-bid" type="range" min={100} max={1200} step={50} value={bid} onChange={event => setBid(Number(event.target.value))} aria-valuetext={money(bid)}/>
        </div>
      </div>
      <div className="p-hero-bottom"><span>01 — {pick(lang,"O‘rningizni o‘zingiz belgilang","YOUR POSITION. YOUR CHOICE.","ВАША ПОЗИЦИЯ. ВАШ ВЫБОР.")}</span><a href="#how">{pick(lang,"Yana ko‘proq","Discover more","Узнать больше")}<ArrowRight size={14}/></a></div>
    </section>
    <div className="p-value-strip"><div className="p-container">{[
      [ShieldCheck,pick(lang,"Avval moderatsiya","Moderation first","Сначала модерация")],
      [Zap,pick(lang,"Jonli reyting","Live rankings","Живой рейтинг")],
      [Globe2,pick(lang,"Har qanday qurilmada","Every screen, everywhere","На любом устройстве")],
      [ChartNoAxesCombined,pick(lang,"Haqiqiy ko‘rsatkichlar","Actual performance","Реальные показатели")]
    ].map(([Icon,label],index) => { const Glyph=Icon as typeof Zap; return <span key={index}><Glyph size={18}/>{label as string}</span>; })}</div></div>
    <section id="how" className="p-section p-container">
      <div className="p-section-heading"><div><span className="p-eyebrow p-muted">01 / {pick(lang,"QANDAY ISHLAYDI","HOW IT WORKS","КАК ЭТО РАБОТАЕТ")}</span><h2>{pick(lang,"Oddiy qoida.","Simple rules.","Простые правила.")}<br/><span className="p-dim">{pick(lang,"Sizda to‘liq nazorat.","You’re in control.","Контроль у вас.")}</span></h2></div><p>{pick(lang,"Murakkab sozlamalarsiz. Reklamadan natijagacha bo‘lgan yo‘l bir joyda.","No complicated setup. One clear path from your first ad to your next move.","Без сложных настроек. Понятный путь от первого объявления до следующего шага.")}</p></div>
      <div className="p-step-grid">{[
        [Layers3,pick(lang,"Brendingizni tanishtiring","Introduce your brand","Представьте свой бренд"),pick(lang,"Rasm, qisqa matn va saytingiz manzilini qo‘shing. Mos toifani tanlang.","Add an image, a short description and your website. Choose the right category.","Добавьте изображение, короткое описание и сайт. Выберите категорию.")],
        [SlidersHorizontal,pick(lang,"Taklifingizni belgilang","Make your move","Задайте ставку"),pick(lang,"Kunlik stavka va muddatni tanlang. Jami xarajatni oldindan ko‘ring.","Choose your daily bid and duration. See the full placement price up front.","Выберите дневную ставку и срок. Сразу увидьте стоимость размещения.")],
        [MoveUpRight,pick(lang,"Faollashing va kuzating","Go live. Keep growing.","Запускайте и наблюдайте"),pick(lang,"Moderatsiya va to‘lovdan keyin reklamangiz ishga tushadi. Natijani kabinetda kuzating.","After approval and payment, your ad goes live. Follow its performance in your dashboard.","После проверки и оплаты реклама запускается. Отслеживайте результаты в кабинете.")]
      ].map(([Icon,title,body],index) => { const Glyph=Icon as typeof Zap; return <article className="p-step-card" key={index}><div className="p-step-card-top"><Glyph size={24}/><span>0{index+1}</span></div><h3>{title as string}</h3><p>{body as string}</p><div className="p-step-line"/></article>; })}</div>
    </section>
    <section className="p-product-section p-container">
      <div className="p-product-copy"><span className="p-eyebrow">{pick(lang,"KATTA RASMNI KO‘RING","SEE THE BIGGER PICTURE","ВИДЕТЬ ПОЛНУЮ КАРТИНУ")}</span><h2>{pick(lang,"Har bir qaror.","Every decision.","Каждое решение.")}<br/><span className="p-dim">{pick(lang,"Aniq ma’lumot bilan.","Backed by clarity.","На основе данных.")}</span></h2><p>{pick(lang,"O‘rningiz, reklama holati va natijalar — bir qarashda. Kerakli vaqtda kerakli amal.","Your position, ad status and results at a glance. The right action at the right moment.","Позиция, статус и результаты — с первого взгляда. Нужное действие в нужный момент.")}</p>
        <ul className="p-check-list"><li><Check/>{pick(lang,"Ko‘rilish va bosishlarni kuzating","Follow views and clicks","Отслеживайте просмотры и клики")}</li><li><Check/>{pick(lang,"Raqobatchilar taklifini solishtiring","Compare competing bids","Сравнивайте ставки конкурентов")}</li><li><Check/>{pick(lang,"Muddat va xarajatni boshqaring","Stay on top of time and spend","Контролируйте сроки и расходы")}</li></ul>
        <Link href="/dashboard/demo" className="p-text-link">{pick(lang,"Demo kabinetni ochish","Open the demo dashboard","Открыть демо-кабинет")}<ArrowUpRight size={18}/></Link>
      </div>
      <div className="p-product-preview"><div className="p-preview-top"><span className="p-mini-logo">P</span><b>{pick(lang,"Umumiy holat","Overview","Обзор")}</b><span className="p-demo-tag">{pick(lang,"NAMUNA","DEMO","ПРИМЕР")}</span></div><div className="p-preview-metrics"><div><span>{pick(lang,"Ko‘rilish","Impressions","Показы")}</span><strong>12,480</strong><small>↑ 18.6%</small></div><div><span>{pick(lang,"Bosish","Clicks","Клики")}</span><strong>486</strong><small>↑ 12.4%</small></div><div><span>CTR</span><strong>3.89<span>%</span></strong><small>{pick(lang,"Namuna ma’lumot","Sample data","Пример данных")}</small></div></div><div className="p-mini-chart"><div className="p-chart-grid"/><svg viewBox="0 0 560 150" fill="none" aria-hidden="true"><defs><linearGradient id="preview-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#9b75ff" stopOpacity=".3"/><stop offset="1" stopColor="#9b75ff" stopOpacity="0"/></linearGradient></defs><path d="M0 126 C30 125 25 95 62 103 S115 136 150 95 S190 107 225 80 S270 108 310 63 S350 85 395 41 S440 56 470 26 S525 40 560 8 V150 H0Z" fill="url(#preview-fill)"/><path d="M0 126 C30 125 25 95 62 103 S115 136 150 95 S190 107 225 80 S270 108 310 63 S350 85 395 41 S440 56 470 26 S525 40 560 8" stroke="#B79AFF" strokeWidth="3"/></svg></div><div className="p-preview-row"><span className="p-brand-avatar violet">P</span><div><b>{pick(lang,"Sizning reklamangiz","Your campaign","Ваша кампания")}</b><small>{pick(lang,"Texnologiya","Technology","Технологии")}</small></div><span className="p-status-badge active">{pick(lang,"Faol","Active","Активно")}</span><strong>#2</strong></div></div>
    </section>
    <section id="categories" className="p-section p-container"><div className="p-section-heading"><div><span className="p-eyebrow p-muted">02 / {pick(lang,"O‘Z MAYDONINGIZNI TOPING","FIND YOUR SPACE","НАЙДИТЕ СВОЮ НИШУ")}</span><h2>{pick(lang,"Har bir brendga","A place for","Место для")}<br/><span className="p-dim">{pick(lang,"o‘z maydoni.","every kind of brand.","каждого бренда.")}</span></h2></div><Link href="/browse" className="p-text-link">{pick(lang,"Barcha reklamalar","Explore all ads","Все объявления")}<ArrowUpRight size={18}/></Link></div>
      <div className="p-category-grid">{CATEGORY_IDS.map((category,index) => { const Icon=icons[index]; return <Link key={category} href={`/browse?category=${category}`} className="p-category-tile"><Icon size={24}/><span>{categoryName(category,lang)}</span><ArrowUpRight size={16}/></Link>; })}</div>
    </section>
    <section id="pricing" className="p-pricing-section p-container"><div><span className="p-eyebrow">{pick(lang,"ANIQ NARX. ANIQ TANLOV.","CLEAR PRICE. CLEAR CHOICE.","ПОНЯТНАЯ ЦЕНА. ВАШ ВЫБОР.")}</span><h2>{pick(lang,"Byudjet sizniki.","Your budget.","Ваш бюджет.")}<br/><span className="p-dim">{pick(lang,"Qaror ham sizniki.","Your next move.","Ваше решение.")}</span></h2><p>{pick(lang,"Kunlik $1 dan boshlang. Reklama joylashuvi narxi — kunlik taklif × muddat. To‘lovdan oldin hammasi aniq.","Start from $1 a day. Placement price is your daily bid × duration. Know the cost before you commit.","Начните с $1 в день. Стоимость размещения — дневная ставка × срок. Все расходы известны до оплаты.")}</p><span className="p-price-note"><ShieldCheck size={17}/>{pick(lang,"To‘lov faqat moderatsiyadan keyin","Pay only after moderation","Оплата только после модерации")}</span></div>
      <div className="p-price-calculator"><div className="p-calculator-heading"><span>{pick(lang,"Joylashuv kalkulyatori","Placement calculator","Калькулятор размещения")}</span><SlidersHorizontal size={18}/></div><label htmlFor="price-bid" className="p-slider-label"><span>{pick(lang,"Kunlik taklif","Daily bid","Дневная ставка")}</span><strong>{money(bid)}<small> / {pick(lang,"kun","day","день")}</small></strong></label><input id="price-bid" type="range" min={100} max={1200} step={50} value={bid} onChange={event => setBid(Number(event.target.value))}/><div className="p-duration-buttons" aria-label={pick(lang,"Muddat","Duration","Срок")}>{[7,14,30].map(day => <button key={day} aria-pressed={days === day} onClick={() => setDays(day)}>{day} {pick(lang,"kun","days","дней")}</button>)}</div><div className="p-price-total"><div><span>{pick(lang,"Joylashuv narxi","Placement price","Стоимость размещения")}</span><small>{money(bid)} × {days} {pick(lang,"kun","days","дней")}</small></div><strong>{money(bid*days)}</strong></div><Link href={`/create?minBid=${bid}&days=${days}`} className="p-btn p-btn-primary">{pick(lang,"Shu taklif bilan boshlash","Start with this bid","Начать с этой ставкой")}<ArrowUpRight size={18}/></Link><p className="p-fine-print">{pick(lang,"Mavjud soliqlar va yakuniy to‘lov summasi to‘lov oynasida ko‘rsatiladi.","Applicable taxes and the final charge are shown at checkout.","Применимые налоги и итоговая сумма отображаются при оплате.")}</p></div>
    </section>
    <section className="p-section p-container p-faq-section"><div><span className="p-eyebrow p-muted">03 / FAQ</span><h2>{pick(lang,"Savollaringiz","Your questions,","Ваши вопросы —")}<br/><span className="p-dim">{pick(lang,"javobsiz qolmaydi.","answered.","наши ответы.")}</span></h2><a className="p-text-link" href="mailto:support@primio.com.uz">{pick(lang,"Biz bilan bog‘laning","Talk to us","Свяжитесь с нами")}<ArrowUpRight size={16}/></a></div><div className="p-faq-list">{faqs.map(([question,answer],index) => <div className="p-faq-item" key={question}><button aria-expanded={faq === index} aria-controls={`faq-${index}`} onClick={() => setFaq(faq === index ? null : index)}>{question}<Plus size={18} className={faq === index ? "is-open" : ""}/></button><div id={`faq-${index}`} hidden={faq !== index}><p>{answer}</p></div></div>)}</div></section>
    <section className="p-final-cta p-container"><span className="p-eyebrow">{pick(lang,"KEYINGI O‘RIN — SIZNIKI","THE NEXT SPOT IS YOURS","СЛЕДУЮЩЕЕ МЕСТО — ВАШЕ")}</span><h2>{pick(lang,"Brendingiz ko‘rinsin.","Let your brand be seen.","Пусть ваш бренд заметят.")}<ArrowUpRight/></h2><p>{pick(lang,"Birinchi reklamangizni yarating. Keyingi qadamni birga qo‘yamiz.","Create your first ad. Make your next move with Primio.","Создайте первое объявление. Сделайте следующий шаг с Primio.")}</p><Link href="/create" className="p-btn p-btn-light">{pick(lang,"Hozir boshlash","Get started today","Начать сейчас")}<ArrowUpRight size={18}/></Link><MousePointer2 className="p-cta-cursor"/></section>
    <Footer lang={lang}/>
  </div>;
}